name: test

on:
  push:
    branches:
  pull_request:
  workflow_dispatch:

env:
  TEST_TAG: latest-ci-test

jobs:
  release:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: "v2.2.1"

      - name: Force Delete Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: ${{ env.TEST_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create/Update tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.TEST_TAG }}
          message: "ci test"
          force_push_tag: true
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TEST_TAG }}
          release_name: ${{ env.TEST_TAG }}
          draft: false
          prerelease: false

  publish:
    name: publish ${{ matrix.name }}
    needs:
      - release
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            name: windows-x86_64
            archive: zip
          - target: x86_64-unknown-linux-gnu
            name: linux-x86_64
            archive: tar.gz tar.xz
          - target: x86_64-apple-darwin
            name: darwin-x86_64
            archive: tar.gz

    runs-on: ubuntu-latest
    steps:
      - name: Clone test repository
        uses: actions/checkout@v2
        with:
          repository: ihaiker/idgener
          path: rust-release.test

      - name: Clone action repository
        uses: actions/checkout@v3
        with:
          path: actions
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: ./actions
        name: build ${{ matrix.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_DIR: "${{ github.workspace }}/rust-release.test"
          IS_CI_TEST: true
        with:
          release: ${{ env.TEST_TAG }}
          rust_target: ${{ matrix.target }}
          name: ${{ env.TEST_TAG }}
          archive_suffix: ${{ matrix.name }}
          archive_types: ${{ matrix.archive }}
          extra_files: "etc/log4rs.yaml etc/idgener.yaml README.md README_ZH.md LICENSE"
          minify: true

  clean:
    name: clean release
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Force Delete Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: ${{ env.TEST_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
